"use client";

import { useEffect, useMemo, useState } from "react";

type Scene = { id:number; text:string; duration:number; transition:"fade"|"slide"|"cut" };
const starter = `A small village wakes up at sunrise.
A curious child discovers an old map.
The journey begins toward a hidden valley.`;
const PROJECT_KEY="shree-ai-video-project-v4";
const normaliseScenes=(value:unknown):Scene[]=>{if(!Array.isArray(value))return [];return value.map((s,i)=>({id:i+1,text:typeof s?.text==="string"?s.text.trim():"Scene",duration:typeof s?.duration==="number"?Math.min(8,Math.max(1,s.duration)):3,transition:(s?.transition==="fade"||s?.transition==="slide"||s?.transition==="cut"?s.transition:"fade") as Scene["transition"]})).filter(s=>s.text);};
const blobToDataUrl=(blob:Blob)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(blob);});
const localImageDataUrl=(text:string)=>{const safe=text.replace(/[<>&]/g,m=>({"<":"&lt;",">":"&gt;","&":"&amp;"}[m]||m)).slice(0,120);return "data:image/svg+xml;charset=utf-8,"+encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" width="720" height="1280"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stop-color="#111827"/><stop offset="100%" stop-color="#2563eb"/></linearGradient></defs><rect width="720" height="1280" fill="url(#g)"/><circle cx="590" cy="170" r="120" fill="#ffffff" opacity=".08"/><circle cx="130" cy="1080" r="180" fill="#ffffff" opacity=".06"/><text x="48" y="1080" fill="white" font-family="Arial,sans-serif" font-size="30" font-weight="700">SHREE AI VIDEO</text><foreignObject x="48" y="1120" width="624" height="110"><div xmlns="http://www.w3.org/1999/xhtml" style="color:white;font:24px Arial,sans-serif;line-height:1.3">${safe}</div></foreignObject></svg>`);};
const localVideoBlob=async(text:string,seconds=3)=>{const canvas=document.createElement("canvas");canvas.width=720;canvas.height=1280;const ctx=canvas.getContext("2d")!;const stream=canvas.captureStream(24);const mime=MediaRecorder.isTypeSupported("video/webm;codecs=vp9")?"video/webm;codecs=vp9":"video/webm";const rec=new MediaRecorder(stream,{mimeType:mime});const chunks:BlobPart[]=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);const done=new Promise<void>(resolve=>rec.onstop=()=>resolve());rec.start();const end=Date.now()+Math.max(2,Math.min(8,seconds))*1000;const draw=()=>{const p=Math.min(1,Math.max(0,(Date.now()-(end-Math.max(2,Math.min(8,seconds))*1000))/(Math.max(2,Math.min(8,seconds))*1000));ctx.fillStyle="#0b1220";ctx.fillRect(0,0,720,1280);const g=ctx.createLinearGradient(0,0,720,1280);g.addColorStop(0,"#172554");g.addColorStop(1,"#2563eb");ctx.fillStyle=g;ctx.fillRect(0,0,720,1280);ctx.globalAlpha=.12;ctx.beginPath();ctx.arc(600,180,120+40*p,0,Math.PI*2);ctx.fillStyle="white";ctx.fill();ctx.globalAlpha=1;ctx.fillStyle="white";ctx.font="bold 30px Arial";ctx.fillText("SHREE AI VIDEO",48,1080);ctx.font="24px Arial";const words=text.slice(0,150);ctx.fillText(words,48,1130);if(Date.now()<end)requestAnimationFrame(draw);else rec.stop();};draw();await done;stream.getTracks().forEach(t=>t.stop());return new Blob(chunks,{type:mime});};


export default function Home() {
  const [script,setScript]=useState(starter);
  const [scenes,setScenes]=useState<Scene[]>([]);
  const [images,setImages]=useState<Record<number,string>>({});
  const [sceneVideos,setSceneVideos]=useState<Record<number,string>>({});
  const [status,setStatus]=useState("");
  const [exportUrl,setExportUrl]=useState("");
  const [aiVideoUrl,setAiVideoUrl]=useState("");
  const [voice,setVoice]=useState("default");
  const [busyImage,setBusyImage]=useState<number|null>(null);
  const [busyVideo,setBusyVideo]=useState(false);
  const [busySceneVideo,setBusySceneVideo]=useState<number|null>(null);
  const [duration,setDuration]=useState(4);
  const [musicUrl,setMusicUrl]=useState("");
  const [musicName,setMusicName]=useState("");
  const [captions,setCaptions]=useState(true);
  const [captionStyle,setCaptionStyle]=useState<"box"|"clean"|"neon">("box");
  const [previewScene,setPreviewScene]=useState(0);
  const [previewPlaying,setPreviewPlaying]=useState(false);
  const [selectedScene,setSelectedScene]=useState(0);
  const [aspect,setAspect]=useState<"9:16"|"16:9"|"1:1">("9:16");
  const [renderProgress,setRenderProgress]=useState(0);
  const [rendering,setRendering]=useState(false);
  const [dragScene,setDragScene]=useState<number|null>(null);
  const [dirty,setDirty]=useState(false);
  const [idea,setIdea]=useState("");
  const [busyScript,setBusyScript]=useState(false);
  const [sceneAudios,setSceneAudios]=useState<Record<number,string>>({});
  const [busyVoice,setBusyVoice]=useState<number|null>(null);
  const [autoBusy,setAutoBusy]=useState(false);
  const [autoProgress,setAutoProgress]=useState(0);
  const [timelineZoom,setTimelineZoom]=useState(1);
  const [musicVolume,setMusicVolume]=useState(.22);
  const [voiceVolume,setVoiceVolume]=useState(.95);
  const [template,setTemplate]=useState("reel");
  const [captionPosition,setCaptionPosition]=useState<"top"|"center"|"bottom">("bottom");
  const [captionSize,setCaptionSize]=useState(28);
  const [autoCaptions,setAutoCaptions]=useState(true);
  const [captionCase,setCaptionCase]=useState<"normal"|"upper"|"lower">("normal");
  const [history,setHistory]=useState<string[]>([]); const [historyIndex,setHistoryIndex]=useState(-1);
  useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="s"){e.preventDefault();saveProject()} if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==="z"){e.preventDefault();if(e.shiftKey){document.querySelector<HTMLButtonElement>(".undoTools button:last-child")?.click()}else document.querySelector<HTMLButtonElement>(".undoTools button:first-child")?.click()} if(e.key==="Escape")setSelectedScene(-1)};window.addEventListener("keydown",onKey);return()=>window.removeEventListener("keydown",onKey)},[]);
  const [trimStart,setTrimStart]=useState<Record<number,number>>({});
  const [trimEnd,setTrimEnd]=useState<Record<number,number>>({});

  const sceneCount=useMemo(()=>script.split(/\n+/).filter(s=>s.trim()).length,[script]);
  const totalDuration=useMemo(()=>scenes.reduce((n,s)=>n+s.duration,0),[scenes]);
  const editedDuration=useMemo(()=>scenes.reduce((n,s)=>n+Math.max(.5,s.duration-(trimStart[s.id]||0)-(trimEnd[s.id]||0)),0),[scenes,trimStart,trimEnd]);
  const activePreview=useMemo(()=>scenes[previewScene]||null,[scenes,previewScene]);
  const activeEdit=useMemo(()=>scenes[selectedScene]||null,[scenes,selectedScene]);
  useEffect(()=>{if(previewScene>=scenes.length)setPreviewScene(Math.max(0,scenes.length-1));},[scenes.length,previewScene]);
  useEffect(()=>{if(selectedScene>=scenes.length)setSelectedScene(Math.max(0,scenes.length-1));},[scenes.length,selectedScene]);
  useEffect(()=>{if(!previewPlaying||!scenes.length)return;const t=window.setTimeout(()=>setPreviewScene(i=>i+1>=scenes.length?0:i+1),(activePreview?.duration||3)*1000);return()=>window.clearTimeout(t);},[previewPlaying,previewScene,scenes.length,activePreview?.duration]);

  useEffect(()=>{try{const raw=localStorage.getItem(PROJECT_KEY);if(!raw)return;const p=JSON.parse(raw);if(typeof p.script==="string")setScript(p.script);setScenes(normaliseScenes(p.scenes));if(p.images&&typeof p.images==="object")setImages(p.images);if(p.sceneVideos&&typeof p.sceneVideos==="object")setSceneVideos(p.sceneVideos);if(p.sceneAudios&&typeof p.sceneAudios==="object")setSceneAudios(p.sceneAudios);if(typeof p.musicName==="string")setMusicName(p.musicName);if(typeof p.captions==="boolean")setCaptions(p.captions);if(["box","clean","neon"].includes(p.captionStyle))setCaptionStyle(p.captionStyle);if(typeof p.timelineZoom==="number")setTimelineZoom(Math.min(2,Math.max(.5,p.timelineZoom)));if(typeof p.musicVolume==="number")setMusicVolume(Math.min(1,Math.max(0,p.musicVolume)));if(typeof p.voiceVolume==="number")setVoiceVolume(Math.min(1,Math.max(0,p.voiceVolume)));if(p.trimStart)setTrimStart(p.trimStart);if(p.trimEnd)setTrimEnd(p.trimEnd);if(["top","center","bottom"].includes(p.captionPosition))setCaptionPosition(p.captionPosition);if(typeof p.captionSize==="number")setCaptionSize(Math.min(48,Math.max(18,p.captionSize)));if(typeof p.autoCaptions==="boolean")setAutoCaptions(p.autoCaptions);if(["normal","upper","lower"].includes(p.captionCase))setCaptionCase(p.captionCase);setDirty(false);}catch{}},[]);
  useEffect(()=>{if(!dirty)return;const timer=window.setTimeout(()=>{try{localStorage.setItem(PROJECT_KEY,JSON.stringify({version:7,script,scenes,images,sceneVideos,sceneAudios,musicName,captions,captionStyle,timelineZoom,musicVolume,voiceVolume,trimStart,trimEnd,captionPosition,captionSize,autoCaptions,captionCase}));setDirty(false);}catch{}},900);return()=>window.clearTimeout(timer);},[dirty,script,scenes,images,sceneVideos,sceneAudios,musicName,captions,captionStyle,timelineZoom,musicVolume,voiceVolume,trimStart,trimEnd,captionPosition,captionSize,autoCaptions,captionCase]);
  const markDirty=()=>setDirty(true);

  const effectiveDuration=(s:Scene)=>Math.max(.5,s.duration-(trimStart[s.id]||0)-(trimEnd[s.id]||0));
  const snapshot=()=>JSON.stringify({script,scenes,images,sceneVideos,sceneAudios,trimStart,trimEnd}); const pushHistory=()=>{const snap=snapshot();setHistory(h=>{const n=h.slice(0,historyIndex+1);n.push(snap);return n.slice(-30)});setHistoryIndex(i=>Math.min(i+1,29))};
  const updateTrim=(id:number,side:"start"|"end",value:number)=>{const s=scenes.find(x=>x.id===id);if(!s)return;const max=Math.max(0,s.duration-.5);if(side==="start")setTrimStart(v=>({...v,[id]:Math.min(value,max-(trimEnd[id]||0))}));else setTrimEnd(v=>({...v,[id]:Math.min(value,max-(trimStart[id]||0))}));markDirty()};
  const applyTemplate=(kind:string)=>{const presets:Record<string,string[]>={reel:["Hook: introduce the topic with a strong visual.","Main point: explain the key idea clearly.","Proof: show an example or result.","Payoff: reveal the takeaway.","CTA: end with a short call to action."],promo:["Opening: introduce the product or service.","Feature: highlight the main benefit.","Experience: show the product in use.","Trust: add a reason to believe.","CTA: invite the viewer to act."],news:["Headline: present the key development.","Context: explain what happened and where.","Details: summarize the important facts.","Impact: explain who or what is affected.","Closing: give the concise takeaway."],story:["Opening: introduce the character and setting.","Conflict: present the problem or mystery.","Journey: show the character moving forward.","Climax: reveal the major turning point.","Ending: close the story with a memorable moment."]};setScript((presets[kind]||presets.reel).join("\n"));setScenes([]);setSelectedScene(0);setPreviewScene(0);markDirty();setStatus(`${kind} template applied — create scenes to continue.`);};
  const buildScenes=()=>{setSceneAudios({});setSceneVideos({});const next=script.split(/\n+/).map(s=>s.trim()).filter(Boolean).map((text,id)=>({id:id+1,text,duration:3,transition:"fade" as const}));setScenes(next);setSelectedScene(0);setPreviewScene(0);markDirty();setStatus(next.length?`${next.length} scenes ready • ${next.length*3}s timeline`:"Write at least one scene line first.");setExportUrl("");setAiVideoUrl("");};
  const updateScene=(id:number,patch:Partial<Scene>)=>{setScenes(v=>v.map(s=>s.id===id?{...s,...patch}:s));markDirty();};
  const remapImages=(next:Scene[],source:Record<number,string>)=>{const out:Record<number,string>={};next.forEach(s=>{if(source[s.id])out[s.id]=source[s.id];});return out;};
  const duplicateScene=(id:number)=>{const i=scenes.findIndex(s=>s.id===id);if(i<0)return;const oldImages={...images};const next=[...scenes.slice(0,i+1),{...scenes[i]},...scenes.slice(i+1)].map((s,n)=>({...s,id:n+1}));const duplicatedImage=oldImages[id];if(duplicatedImage)oldImages[i+2]=duplicatedImage;setImages(remapImages(next,oldImages));setSceneAudios(v=>{const out:Record<number,string>={};next.forEach(s=>{if(v[s.id])out[s.id]=v[s.id]});return out;});setSceneVideos(v=>{const out:Record<number,string>={};next.forEach(s=>{if(v[s.id])out[s.id]=v[s.id]});return out;});setScenes(next);setSelectedScene(i+1);setPreviewScene(i+1);markDirty();setStatus(`Scene ${id} duplicated.`);};
  const splitScene=(id:number)=>{const i=scenes.findIndex(s=>s.id===id);if(i<0)return;const s=scenes[i];if(s.duration<2){setStatus("Scene must be at least 2 seconds to split.");return;}const first={...s,duration:Math.max(1,Math.round((s.duration/2)*2)/2),text:s.text.trim()};const second={...s,duration:Math.max(1,Math.round((s.duration/2)*2)/2),text:s.text.trim()};const next=[...scenes.slice(0,i),first,second,...scenes.slice(i+1)].map((x,n)=>({...x,id:n+1}));setImages({});setSceneVideos({});setSceneAudios({});setScenes(next);setSelectedScene(i+1);setPreviewScene(i+1);markDirty();setStatus("Scene split into two clips.");};
  const moveScene=(id:number,dir:-1|1)=>{const i=scenes.findIndex(s=>s.id===id),j=i+dir;if(i<0||j<0||j>=scenes.length)return;reorderScene(i,j);};
  const reorderScene=(from:number,to:number)=>{if(from===to||from<0||to<0||from>=scenes.length||to>=scenes.length)return;const order=[...scenes];const [item]=order.splice(from,1);order.splice(to,0,item);const oldImages={...images};const next=order.map((s,i)=>({...s,id:i+1}));const source:Record<number,string>={};order.forEach((s,i)=>{if(oldImages[s.id])source[i+1]=oldImages[s.id];});setImages(remapImages(next,source));setSceneAudios(v=>{const out:Record<number,string>={};order.forEach((s,i)=>{if(v[s.id])out[i+1]=v[s.id]});return out;});setScenes(next);setSelectedScene(to);setPreviewScene(to);markDirty();setStatus(`Scene moved to position ${to+1}.`);};
  const removeScene=(id:number)=>{const remap=(source:Record<number,string>)=>{const out:Record<number,string>={};scenes.filter(s=>s.id!==id).forEach((s,i)=>{if(source[s.id])out[i+1]=source[s.id]});return out;};const next=scenes.filter(s=>s.id!==id).map((s,i)=>({...s,id:i+1}));setImages(remap(images));setSceneVideos(remap(sceneVideos));setSceneAudios(remap(sceneAudios));setScenes(next);setSelectedScene(i=>Math.max(0,Math.min(i,next.length-1)));setPreviewScene(i=>Math.max(0,Math.min(i,next.length-1)));markDirty();setStatus("Scene removed.");};
  const generateScript=async()=>{if(!idea.trim()){setStatus("Write a video idea first.");return;}setBusyScript(true);setStatus("AI is writing your script…");try{const res=await fetch("/api/generate-script",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({idea,scenes:5})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||"AI script generation failed.");setScript(data.script);setScenes([]);setSelectedScene(0);setPreviewScene(0);markDirty();setStatus("AI script ready — create scenes to continue.");}catch{const local=[`Hook: ${idea.trim()}.`,`Context: explain the main idea behind ${idea.trim()}.`,"Key detail: show a clear example or visual.","Payoff: reveal the main takeaway.","Closing: end with a memorable call to action." ];setScript(local.join("\n"));setScenes([]);setSelectedScene(0);setPreviewScene(0);markDirty();setStatus("AI service unavailable — local script fallback created, so you can continue editing.");}finally{setBusyScript(false);}};
  const generateVoiceover=async(scene:Scene)=>{setBusyVoice(scene.id);setStatus(`Generating AI voice for scene ${scene.id}…`);try{const res=await fetch("/api/generate-voice",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:scene.text})});if(!res.ok)throw new Error("AI voice service unavailable");const data=await blobToDataUrl(await res.blob());setSceneAudios(v=>({...v,[scene.id]:data}));markDirty();setStatus(`AI voice ready for scene ${scene.id}.`);}catch{setSceneAudios(v=>{const n={...v};delete n[scene.id];return n;});speak(scene.text);setStatus(`AI voice service unavailable — browser voice preview is being used for scene ${scene.id}.`);}finally{setBusyVoice(null);}};
  const makeStory=()=>{const topics=["A mysterious signal appears in the night sky.","A young explorer follows the signal into an ancient forest.","Inside the forest, a hidden doorway opens.","The explorer finds a glowing city and discovers its secret.","At sunrise, the journey becomes a new beginning."];setScript(topics.join("\n"));setScenes([]);setSelectedScene(0);setPreviewScene(0);markDirty();setStatus("Story draft created — edit it before rendering.");};
  const saveProject=()=>{try{localStorage.setItem(PROJECT_KEY,JSON.stringify({version:7,script,scenes,images,sceneVideos,sceneAudios,musicName,captions,captionStyle,timelineZoom,musicVolume,voiceVolume,trimStart,trimEnd,captionPosition,captionSize,autoCaptions,captionCase}));setDirty(false);setStatus("Project saved on this device.");}catch{setStatus("Could not save project. Browser storage may be full.");}};
  const exportProject=async()=>{try{setStatus("Preparing portable project…");const portableImages:Record<number,string>={};for(const [id,url] of Object.entries(images)){if(url.startsWith("data:")){portableImages[Number(id)]=url;continue;}try{const res=await fetch(url);const blob=await res.blob();portableImages[Number(id)]=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=reject;reader.readAsDataURL(blob);});}catch{}}const portableAudios:Record<number,string>={};for(const [id,url] of Object.entries(sceneAudios)){if(url.startsWith("data:"))portableAudios[Number(id)]=url;}const portableVideos:Record<number,string>={};for(const [id,url] of Object.entries(sceneVideos)){if(url.startsWith("data:"))portableVideos[Number(id)]=url;}const payload={version:5,exportedAt:new Date().toISOString(),script,scenes,images:portableImages,sceneVideos:portableVideos,sceneAudios:portableAudios,musicName,captions,captionStyle,timelineZoom,musicVolume,voiceVolume,trimStart,trimEnd};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download="shree-ai-video-project.json";a.click();URL.revokeObjectURL(url);setStatus("Portable project exported with scene images.");}catch{setStatus("Could not export project.");}};
  const importProject=(file:File)=>{const reader=new FileReader();reader.onload=()=>{try{const p=JSON.parse(String(reader.result));if(typeof p.script!=="string"||!Array.isArray(p.scenes))throw new Error();setScript(p.script);setScenes(normaliseScenes(p.scenes));setSelectedScene(0);setPreviewScene(0);setImages(p.images&&typeof p.images==="object"?p.images:{});setSceneVideos(p.sceneVideos&&typeof p.sceneVideos==="object"?p.sceneVideos:{});setSceneAudios(p.sceneAudios&&typeof p.sceneAudios==="object"?p.sceneAudios:{});setMusicName(typeof p.musicName==="string"?p.musicName:"");setCaptions(typeof p.captions==="boolean"?p.captions:true);setCaptionStyle(["box","clean","neon"].includes(p.captionStyle)?p.captionStyle:"box");if(typeof p.timelineZoom==="number")setTimelineZoom(Math.min(2,Math.max(.5,p.timelineZoom)));if(typeof p.musicVolume==="number")setMusicVolume(Math.min(1,Math.max(0,p.musicVolume)));if(typeof p.voiceVolume==="number")setVoiceVolume(Math.min(1,Math.max(0,p.voiceVolume)));if(p.trimStart&&typeof p.trimStart==="object")setTrimStart(p.trimStart);if(p.trimEnd&&typeof p.trimEnd==="object")setTrimEnd(p.trimEnd);if(["top","center","bottom"].includes(p.captionPosition))setCaptionPosition(p.captionPosition);if(typeof p.captionSize==="number")setCaptionSize(Math.min(48,Math.max(18,p.captionSize)));if(typeof p.autoCaptions==="boolean")setAutoCaptions(p.autoCaptions);if(["normal","upper","lower"].includes(p.captionCase))setCaptionCase(p.captionCase);setDirty(false);setStatus("Project JSON imported.");}catch{setStatus("Invalid Shree AI Video project file.");}};reader.readAsText(file);};
  const loadProject=()=>{try{const raw=localStorage.getItem(PROJECT_KEY);if(!raw){setStatus("No saved project found.");return;}const p=JSON.parse(raw);setScript(typeof p.script==="string"?p.script:starter);setScenes(normaliseScenes(p.scenes));setSelectedScene(0);setPreviewScene(0);setImages(p.images&&typeof p.images==="object"?p.images:{});setSceneVideos(p.sceneVideos&&typeof p.sceneVideos==="object"?p.sceneVideos:{});setSceneAudios(p.sceneAudios&&typeof p.sceneAudios==="object"?p.sceneAudios:{});setMusicName(typeof p.musicName==="string"?p.musicName:"");setCaptions(typeof p.captions==="boolean"?p.captions:true);setCaptionStyle(["box","clean","neon"].includes(p.captionStyle)?p.captionStyle:"box");if(typeof p.timelineZoom==="number")setTimelineZoom(Math.min(2,Math.max(.5,p.timelineZoom)));if(typeof p.musicVolume==="number")setMusicVolume(Math.min(1,Math.max(0,p.musicVolume)));if(typeof p.voiceVolume==="number")setVoiceVolume(Math.min(1,Math.max(0,p.voiceVolume)));if(p.trimStart&&typeof p.trimStart==="object")setTrimStart(p.trimStart);if(p.trimEnd&&typeof p.trimEnd==="object")setTrimEnd(p.trimEnd);if(["top","center","bottom"].includes(p.captionPosition))setCaptionPosition(p.captionPosition);if(typeof p.captionSize==="number")setCaptionSize(Math.min(48,Math.max(18,p.captionSize)));if(typeof p.autoCaptions==="boolean")setAutoCaptions(p.autoCaptions);if(["normal","upper","lower"].includes(p.captionCase))setCaptionCase(p.captionCase);setDirty(false);setStatus("Saved project loaded.");}catch{setStatus("Saved project could not be loaded.");}};
  const speak=(text:string)=>{if(typeof window==="undefined"||!("speechSynthesis" in window)){setStatus("Browser voice is not available.");return;}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=voice==="slow"?.85:voice==="fast"?1.15:1;window.speechSynthesis.speak(u);setStatus("Voice preview playing…");};
  const attachImage=async(id:number,file:File)=>{try{const data=await blobToDataUrl(file);setImages(v=>({...v,[id]:data}));markDirty();setStatus(`Image added to scene ${id}.`);}catch{setStatus("Could not read image.");}};
  const attachMusic=(file:File)=>{setMusicUrl(URL.createObjectURL(file));setMusicName(file.name);markDirty();setStatus("Background music selected for this session.");};

  const generateImage=async(scene:Scene)=>{setBusyImage(scene.id);setStatus(`Generating AI image for scene ${scene.id}…`);try{const res=await fetch("/api/generate-image",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:`${scene.text}. Cinematic vertical short-video frame, detailed environment, consistent story character, dramatic lighting.`})});if(!res.ok)throw new Error("AI image service unavailable");const data=await blobToDataUrl(await res.blob());setImages(v=>({...v,[scene.id]:data}));markDirty();setStatus(`AI image ready for scene ${scene.id}.`);}catch{setImages(v=>({...v,[scene.id]:localImageDataUrl(scene.text)}));markDirty();setStatus(`AI image service unavailable — local visual fallback created for scene ${scene.id}.`);}finally{setBusyImage(null);}};
  const generateSceneVideo=async(scene:Scene)=>{setBusySceneVideo(scene.id);setStatus(`Generating AI video for scene ${scene.id}…`);try{const res=await fetch("/api/generate-video",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:`${scene.text}. Cinematic vertical short-video scene, coherent character and environment, smooth motion, no text overlays.`,duration:Math.min(8,Math.max(2,Math.round(scene.duration)))})});if(!res.ok)throw new Error("AI video service unavailable");const data=await blobToDataUrl(await res.blob());setSceneVideos(v=>({...v,[scene.id]:data}));markDirty();setStatus(`AI video ready for scene ${scene.id}.`);}catch{const blob=await localVideoBlob(scene.text,scene.duration);const data=await blobToDataUrl(blob);setSceneVideos(v=>({...v,[scene.id]:data}));markDirty();setStatus(`AI video service unavailable — local motion-video fallback created for scene ${scene.id}.`);}finally{setBusySceneVideo(null);}};
  const generateAllMedia=async()=>{if(!scenes.length){setStatus("Create scenes first.");return;}if(autoBusy)return;setAutoBusy(true);setAutoProgress(0);setStatus("Generating images and AI voices for all scenes…");try{for(let i=0;i<scenes.length;i++){const scene=scenes[i];setStatus("Generating scene "+scene.id+" of "+scenes.length+"…");if(!images[scene.id]){const res=await fetch("/api/generate-image",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:`${scene.text}. Cinematic vertical short-video frame, detailed environment, consistent story character, dramatic lighting.`})});if(!res.ok)throw new Error("Image generation failed for scene "+scene.id);const data=await blobToDataUrl(await res.blob());setImages(v=>({...v,[scene.id]:data}));}if(!sceneAudios[scene.id]){const res=await fetch("/api/generate-voice",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({text:scene.text})});if(!res.ok)throw new Error("Voice generation failed for scene "+scene.id);const data=await blobToDataUrl(await res.blob());setSceneAudios(v=>({...v,[scene.id]:data}));}setAutoProgress(Math.round(((i+1)/scenes.length)*100));}markDirty();setStatus("All scene media is ready — render your video.");}catch(err){setStatus(err instanceof Error?err.message:"Automatic media generation failed.");}finally{setAutoBusy(false);}};
  const generateVideo=async()=>{if(!scenes.length){setStatus("Create scenes first.");return;}setBusyVideo(true);setAiVideoUrl("");setStatus("Generating AI video… this can take a while.");try{const prompt=scenes.map(s=>s.text).join(" ");const res=await fetch("/api/generate-video",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:`${prompt}. Create a cinematic vertical social video, 9:16 composition, coherent visual story.`,duration})});if(!res.ok)throw new Error("AI video service unavailable");setAiVideoUrl(URL.createObjectURL(await res.blob()));setStatus("AI video ready — preview or download it below.");}catch{const blob=await localVideoBlob(scenes.map(s=>s.text).join(" "),duration);setAiVideoUrl(URL.createObjectURL(blob));setStatus("AI video service unavailable — local motion-video fallback created. Connect the AI backend for generated video.");}finally{setBusyVideo(false);}};

  const exportVideo=async()=>{
    if(!scenes.length){setStatus("Create scenes first.");return;}
    if(rendering)return;
    setRendering(true);setRenderProgress(0);
    setStatus(musicUrl?"Rendering timeline with mixed background music…":"Rendering timeline…");
    const canvas=document.createElement("canvas");const dims=aspect==="16:9"?[1280,720]:aspect==="1:1"?[1080,1080]:[720,1280];canvas.width=dims[0];canvas.height=dims[1];const ctx=canvas.getContext("2d")!;
    const videoStream=canvas.captureStream(30);let audioContext:AudioContext|undefined;let music:HTMLAudioElement|undefined;let audioDestination:MediaStreamAudioDestinationNode|undefined;const voiceSources:AudioBufferSourceNode[]=[];
    const hasVoice=scenes.some(s=>Boolean(sceneAudios[s.id]));
    if(musicUrl||hasVoice){
      try{
        audioContext=new AudioContext();
        audioDestination=audioContext.createMediaStreamDestination();
        await audioContext.resume();
        if(musicUrl){
          music=new Audio(musicUrl);
          music.loop=true;
          music.volume=musicVolume;
          const musicSource=audioContext.createMediaElementSource(music);
          musicSource.connect(audioDestination);
          musicSource.connect(audioContext.destination);
          await music.play();
        }
        const renderStart=audioContext.currentTime+.15;
        let offset=0;
        for(const scene of scenes){
          const url=sceneAudios[scene.id];
          if(url){
            try{
              const response=await fetch(url);
              const buffer=await audioContext.decodeAudioData(await response.arrayBuffer());
              const source=audioContext.createBufferSource();
              source.buffer=buffer;
              const gain=audioContext.createGain();
              gain.gain.value=voiceVolume;
              source.connect(gain);
              gain.connect(audioDestination);
              voiceSources.push(source);
              source.start(renderStart+offset);
            }catch{}
          }
          offset+=scene.duration;
        }
      }catch{
        setStatus("Audio mixing could not be started; rendering video without audio.");
        audioContext?.close();
        audioContext=undefined;
        audioDestination=undefined;
        music=undefined;
      }
    }
    const tracks=[...videoStream.getVideoTracks(),...(audioDestination?.stream.getAudioTracks()||[])];
    const stream=new MediaStream(tracks);const mime=MediaRecorder.isTypeSupported("video/webm;codecs=vp9,opus")?"video/webm;codecs=vp9,opus":"video/webm";
    const recorder=new MediaRecorder(stream,{mimeType:mime});const chunks:BlobPart[]=[];recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);const done=new Promise<void>(resolve=>recorder.onstop=()=>resolve());recorder.start();
    try{
      for(let index=0;index<scenes.length;index++){const scene=scenes[index],start=performance.now(),sceneDuration=effectiveDuration(scene)*1000,src=images[scene.id],trimIn=trimStart[scene.id]||0,trimOut=trimEnd[scene.id]||0;let img:HTMLImageElement|undefined;
        if(src){img=new Image();img.src=src;await new Promise(r=>{img!.onload=()=>r(null);img!.onerror=()=>r(null);});}
        const clipSrc=sceneVideos[scene.id];let clip:HTMLVideoElement|undefined;
        if(clipSrc){clip=document.createElement("video");clip.src=clipSrc;clip.muted=true;clip.playsInline=true;clip.preload="auto";await new Promise(r=>{clip!.onloadedmetadata=()=>r(null);clip!.onerror=()=>r(null);});try{clip.currentTime=Math.min(trimIn,Math.max(0,(clip.duration||trimIn)-0.05));}catch{}try{await clip.play();}catch{}}
        while(performance.now()-start<sceneDuration){const p=Math.min(1,(performance.now()-start)/sceneDuration);if(clip&&clip.readyState>=2&&Number.isFinite(clip.duration)&&clip.duration>0&&clip.currentTime>=Math.max(trimIn,clip.duration-trimOut-0.02)){try{clip.currentTime=Math.min(trimIn,Math.max(0,clip.duration-0.05));await clip.play();}catch{}}ctx.fillStyle="#07111f";ctx.fillRect(0,0,canvas.width,canvas.height);
          if(clip&&clip.readyState>=2){const scale=1+.04*p,w=canvas.width*scale,h=canvas.height*scale;let x=(canvas.width-w)/2;if(scene.transition==="slide"&&index>0)x+=(1-Math.min(1,p/.45))*canvas.width;ctx.globalAlpha=scene.transition==="fade"?Math.min(1,p/.35):.96;ctx.drawImage(clip,x,(canvas.height-h)/2,w,h);ctx.globalAlpha=1;}
          else if(img){const scale=1+.08*p,w=canvas.width*scale,h=canvas.height*scale;let x=(canvas.width-w)/2;if(scene.transition==="slide"&&index>0)x+=(1-Math.min(1,p/.45))*canvas.width;ctx.globalAlpha=scene.transition==="fade"?Math.min(1,p/.35):.86;ctx.drawImage(img,x,(canvas.height-h)/2,w,h);ctx.globalAlpha=1;}
          const grad=ctx.createLinearGradient(0,canvas.height*.48,0,canvas.height);grad.addColorStop(0,"transparent");grad.addColorStop(1,"rgba(0,0,0,.94)");ctx.fillStyle=grad;ctx.fillRect(0,canvas.height*.48,canvas.width,canvas.height*.52);
          if(captions)drawCaption(ctx,scene.text,captionStyle,p,canvas.width,canvas.height);
          ctx.fillStyle="#9fb3c8";ctx.font="18px system-ui";ctx.textAlign="center";ctx.fillText(`Scene ${scene.id} • Shree AI Video`,canvas.width/2,canvas.height*.95);
          setRenderProgress(Math.min(99,Math.round(((index+(performance.now()-start)/sceneDuration)/scenes.length)*100)));
          await new Promise(r=>requestAnimationFrame(r));
        }
      }
    }finally{music?.pause();if(music)music.currentTime=0;voiceSources.forEach(s=>{try{s.stop()}catch{}});audioContext?.close();recorder.stop();setRendering(false);}
    await done;const blob=new Blob(chunks,{type:"video/webm"});setExportUrl(URL.createObjectURL(blob));setRenderProgress(100);setStatus(`Final video ready • ${totalDuration}s • ${aspect} • ${captions?"captions on":"captions off"}`);
  };

  return <main>
    <header><div className="brand"><span>✦</span><div><b>Shree AI Video</b><small>AI Video Creation Studio</small></div></div><span className="pill">{dirty?"UNSAVED":"SAVED"} • LOCAL + AI</span></header>
    <section className="hero"><div><p className="eyebrow">IDEA → SCRIPT → TIMELINE → AI MEDIA → VIDEO</p><h1>Make vertical videos from an idea.</h1><p className="sub">Build scenes, control timing, add captions, music and AI voice, generate scene-by-scene AI video, save projects and render.</p></div></section>
    <section className="card templatePanel"><div className="cardHead"><div><h2>✨ Templates</h2><p className="timelineMeta">Start faster with a ready-made structure.</p></div></div><div className="templateButtons">{["reel","promo","news","story"].map(k=><button key={k} className={template===k?"activeTemplate":""} onClick={()=>{setTemplate(k);applyTemplate(k)}}>{k==="reel"?"🎬 Reel":k==="promo"?"📣 Promo":k==="news"?"📰 News":"📖 Story"}</button>)}</div></section>
  <section className="card aiScriptPanel"><div className="aiScriptInput"><div><b>AI script generator</b><p>Describe your video idea and turn it into editable scenes.</p></div><textarea value={idea} onChange={e=>setIdea(e.target.value)} placeholder="Example: A 30-second motivational video about never giving up." /></div><div className="aiScriptActions"><button className="primary" onClick={generateScript} disabled={busyScript}>{busyScript?"Writing…":"✨ Generate AI script"}</button><span>Uses your server-side AI key.</span></div></section>
    <section className="toolbar card">
      <div><div><b>AI-style story assistant</b><p>Creates a ready-to-edit scene outline locally.</p></div><button onClick={makeStory}>✨ Generate story</button></div>
      <div><div><b>Project</b><p>Save/load your current work on this device.</p></div><div className="projectBtns"><button onClick={saveProject}>Save</button><button onClick={loadProject}>Load</button><button onClick={exportProject}>Export</button><label className="mini upload">Import<input type="file" accept="application/json,.json" onChange={e=>{const f=e.target.files?.[0];if(f)importProject(f);e.currentTarget.value=""}}/></label></div></div>
      <div><div><b>Voice preview</b><p>Uses your browser’s built-in speech engine.</p></div><select value={voice} onChange={e=>setVoice(e.target.value)}><option value="default">Normal</option><option value="slow">Slow</option><option value="fast">Fast</option></select></div>
      <div><div><b>Background music</b><p>{musicName||"Optional audio file for the final render."}</p></div><label className="upload">Choose music<input type="file" accept="audio/*" onChange={e=>{const f=e.target.files?.[0];if(f)attachMusic(f)}}/></label></div>
    </section>
    <section className="card captionPanel"><div><b>Captions</b><p>Burn scene text directly into the exported video.</p></div><label className="toggle"><input type="checkbox" checked={captions} onChange={e=>{setCaptions(e.target.checked);markDirty()}}/><span>On</span></label><div className="audioControls"><label>Music <input type="range" min="0" max="1" step=".05" value={musicVolume} onChange={e=>{setMusicVolume(Number(e.target.value));markDirty()}}/></label><label>Voice <input type="range" min="0" max="1" step=".05" value={voiceVolume} onChange={e=>{setVoiceVolume(Number(e.target.value));markDirty()}}/></label></div><div className="captionControls"><label>Auto captions <input type="checkbox" checked={autoCaptions} onChange={e=>{setAutoCaptions(e.target.checked);markDirty()}}/></label><label>Case <select value={captionCase} onChange={e=>{setCaptionCase(e.target.value as "normal"|"upper"|"lower");markDirty()}}><option value="normal">Normal</option><option value="upper">UPPERCASE</option><option value="lower">lowercase</option></select></label><label>Position <select value={captionPosition} onChange={e=>{setCaptionPosition(e.target.value as "top"|"center"|"bottom");markDirty()}}><option value="top">Top</option><option value="center">Center</option><option value="bottom">Bottom</option></select></label><label>Size <input type="range" min="18" max="48" value={captionSize} onChange={e=>{setCaptionSize(Number(e.target.value));markDirty()}}/></label></div><select value={captionStyle} onChange={e=>{setCaptionStyle(e.target.value as typeof captionStyle);markDirty()}} disabled={!captions}><option value="box">Classic box</option><option value="clean">Clean</option><option value="neon">Highlight</option></select></section>

    <section className="card previewPanel"><div className="cardHead"><div><h2>Live preview</h2><p className="timelineMeta">Scene {activePreview?.id||0} of {scenes.length} • {activePreview?.duration||0}s</p></div><div className="previewBtns"><button onClick={()=>setPreviewScene(i=>Math.max(0,i-1))} disabled={!scenes.length}>‹</button><button className="primary" onClick={()=>setPreviewPlaying(v=>!v)} disabled={!scenes.length}>{previewPlaying?"Pause":"▶ Preview"}</button><button onClick={()=>setPreviewScene(i=>scenes.length?Math.min(scenes.length-1,i+1):0)} disabled={!scenes.length}>›</button></div></div><div className="previewStage">{activePreview&&<>{sceneVideos[activePreview.id]?<video src={sceneVideos[activePreview.id]} muted playsInline autoPlay loop />:images[activePreview.id]?<img src={images[activePreview.id]} alt="" />:<div className="previewPlaceholder">✦<span>Add or generate an image for this scene</span></div>}<div className="previewOverlay"><span>Scene {activePreview.id}</span>{captions&&<strong className={captionStyle}>{activePreview.text}</strong>}</div></>}</div>{scenes.length>0&&<input className="previewScrub" type="range" min="0" max={scenes.length-1} value={previewScene} onChange={e=>{setPreviewPlaying(false);setPreviewScene(Number(e.target.value))}} />}</section>

    <section className="card timeline"><div className="cardHead"><div><h2>1. Timeline</h2><p className="timelineMeta">{scenes.length} scenes • {editedDuration.toFixed(1)}s edited timeline</p></div><button onClick={buildScenes}>Rebuild from script</button></div>{!scenes.length?<div className="empty">Create scenes from your script to start editing the timeline.</div>:<div className="timelineList">{scenes.map((s,i)=><div className={`timelineRow ${selectedScene===i?"selected":""}`} key={s.id} onClick={()=>{setSelectedScene(i);setPreviewScene(i)}} draggable onDragStart={()=>setDragScene(i)} onDragOver={e=>e.preventDefault()} onDrop={()=>{if(dragScene!==null)reorderScene(dragScene,i);setDragScene(null)}}><div className="timelineThumb">{images[s.id]?<img src={images[s.id]} alt=""/>:<span>✦</span>}</div><div className="timelineTrack"><span>Scene {s.id}</span><div className="trackBar"><i style={{width:`${Math.min(100,s.duration/8*100)}%`}}/></div><b>{s.duration}s</b></div><div className="timelineControls"><input aria-label={`Scene ${s.id} duration`} type="range" min="1" max="8" step=".5" value={s.duration} onClick={e=>e.stopPropagation()} onChange={e=>updateScene(s.id,{duration:Number(e.target.value)})}/><select value={s.transition} onClick={e=>e.stopPropagation()} onChange={e=>updateScene(s.id,{transition:e.target.value as Scene["transition"]})}><option value="fade">Fade</option><option value="slide">Slide</option><option value="cut">Cut</option></select><button className="mini" onClick={e=>{e.stopPropagation();moveScene(s.id,-1)}} disabled={i===0}>↑</button><button className="mini" onClick={e=>{e.stopPropagation();moveScene(s.id,1)}} disabled={i===scenes.length-1}>↓</button><button className="mini" onClick={e=>{e.stopPropagation();splitScene(s.id)}}>Split</button><button className="mini" onClick={e=>{e.stopPropagation();duplicateScene(s.id)}}>Copy</button><button className="mini danger" onClick={e=>{e.stopPropagation();removeScene(s.id)}}>Delete</button></div></div>)}</div>}</section>

    <section className="card multiTrack"><div className="cardHead"><div><h2>🎚️ Multi-track timeline</h2><p className="timelineMeta">Video, voice and music stay aligned with your scenes.</p></div><div className="undoTools"><button disabled={historyIndex<=0} onClick={()=>{if(historyIndex<=0)return;const p=JSON.parse(history[historyIndex-1]);setScript(p.script);setScenes(p.scenes);setImages(p.images);setSceneVideos(p.sceneVideos);setSceneAudios(p.sceneAudios);setHistoryIndex(i=>i-1);markDirty()}}>↶ Undo</button><button disabled={historyIndex>=history.length-1} onClick={()=>{if(historyIndex>=history.length-1)return;const p=JSON.parse(history[historyIndex+1]);setScript(p.script);setScenes(p.scenes);setImages(p.images);setSceneVideos(p.sceneVideos);setSceneAudios(p.sceneAudios);setHistoryIndex(i=>i+1);markDirty()}}>↷ Redo</button></div><div className="timelineTools"><label>Zoom <input type="range" min=".5" max="2" step=".25" value={timelineZoom} onChange={e=>{setTimelineZoom(Number(e.target.value));markDirty()}}/></label><span>{Math.round(timelineZoom*100)}% • {totalDuration}s</span></div></div><div className="trackRows"><div className="trackLane"><b>🎬 Video</b><div className="trackSegments">{scenes.map(s=><button key={s.id} className={selectedScene===scenes.findIndex(x=>x.id===s.id)?"trackSegment active":"trackSegment"} style={{flex:effectiveDuration(s)*timelineZoom}} onClick={()=>{const i=scenes.findIndex(x=>x.id===s.id);setSelectedScene(i);setPreviewScene(i)}}>{sceneVideos[s.id]?"AI Video":"Image"}<small>{s.duration}s</small></button>)}</div></div><div className="trackLane"><b>🎙️ Voice</b><div className="trackSegments">{scenes.map(s=><button key={s.id} className="trackSegment" style={{flex:s.duration*timelineZoom}} onClick={()=>{const i=scenes.findIndex(x=>x.id===s.id);setSelectedScene(i)}}>{sceneAudios[s.id]?"AI Voice":"No voice"}<small>{s.duration}s</small></button>)}</div></div><div className="trackLane"><b>🎵 Music</b><div className="trackSegments"><span className="trackSegment musicLane" style={{flex:Math.max(1,totalDuration)*timelineZoom}}>{musicName||"No background music"}<small>{musicName?"Full timeline":"Optional"}</small></span></div></div></div></section>

    <section className="card sceneEditor"><div className="cardHead"><div><h2>Selected scene</h2><p className="timelineMeta">{activeEdit?`Scene ${activeEdit.id} • edit text, timing and transition`:"Select a scene from the timeline."}</p></div>{activeEdit&&<button onClick={()=>{setPreviewScene(selectedScene);setPreviewPlaying(false)}}>Show in preview</button>}</div>{!activeEdit?<div className="empty">Select a timeline scene to edit it here.</div>:<div className="sceneEditorGrid"><label><span>Scene text</span><textarea value={activeEdit.text} onChange={e=>updateScene(activeEdit.id,{text:e.target.value})}/></label><div className="editFields"><label>Duration <input type="range" min="1" max="8" step=".5" value={activeEdit.duration} onChange={e=>updateScene(activeEdit.id,{duration:Number(e.target.value)})}/><b>{activeEdit.duration}s</b></label><label>Trim In <input type="range" min="0" max={Math.max(0,activeEdit.duration-.5-(trimEnd[activeEdit.id]||0))} step=".1" value={trimStart[activeEdit.id]||0} onChange={e=>updateTrim(activeEdit.id,"start",Number(e.target.value))}/><b>{(trimStart[activeEdit.id]||0).toFixed(1)}s</b></label><label>Trim Out <input type="range" min="0" max={Math.max(0,activeEdit.duration-.5-(trimStart[activeEdit.id]||0))} step=".1" value={trimEnd[activeEdit.id]||0} onChange={e=>updateTrim(activeEdit.id,"end",Number(e.target.value))}/><b>{(trimEnd[activeEdit.id]||0).toFixed(1)}s</b></label><small>Edited duration: {effectiveDuration(activeEdit).toFixed(1)}s</small><label>Transition <select value={activeEdit.transition} onChange={e=>updateScene(activeEdit.id,{transition:e.target.value as Scene["transition"]})}><option value="fade">Fade</option><option value="slide">Slide</option><option value="cut">Cut</option></select></label><div className="editActions"><button className="mini" onClick={()=>speak(activeEdit.text)}>🔊 Browser voice</button><button className="mini aiButton" onClick={()=>generateVoiceover(activeEdit)} disabled={busyVoice!==null}>{busyVoice===activeEdit.id?"Generating…":"✨ AI voice"}</button><button className="mini" onClick={()=>splitScene(activeEdit.id)}>Split scene</button><button className="mini" onClick={()=>duplicateScene(activeEdit.id)}>Copy scene</button><button className="mini danger" onClick={()=>removeScene(activeEdit.id)}>Delete</button></div></div></div>}</section>

    <section className="grid">
      <div className="card editor"><div className="cardHead"><h2>2. Your script</h2><button onClick={buildScenes}>Create scenes</button></div><textarea value={script} onChange={e=>{setScript(e.target.value);markDirty()}} placeholder="Write one scene per line…"/><div className="hint">{sceneCount} scene lines • timeline durations can be adjusted above</div></div>
      <div className="card"><div className="cardHead"><h2>3. Scene media</h2><span>{scenes.length}</span></div>{!scenes.length?<div className="empty">Create scenes to unlock narration and AI media.</div>:<div className="scenes">{scenes.map((s,i)=><div className={`scene ${selectedScene===i?"selected":""}`} key={s.id} onClick={()=>{setSelectedScene(i);setPreviewScene(i)}}><div className="sceneNo">{s.id}</div><div className="sceneText"><b>{s.text}</b>{sceneVideos[s.id]&&<video className="sceneImage" src={sceneVideos[s.id]} muted playsInline loop autoPlay />}{images[s.id]&&<img className="sceneImage" src={images[s.id]} alt={`Scene ${s.id}`}/>}</div><div className="actions"><button className="mini" onClick={()=>speak(s.text)}>🔊</button><button className="mini aiButton" onClick={()=>generateImage(s)} disabled={busyImage===s.id}>{busyImage===s.id?"…":"✨ AI image"}</button><button className="mini aiButton" onClick={()=>generateSceneVideo(s)} disabled={busySceneVideo!==null}>{busySceneVideo===s.id?"…":sceneVideos[s.id]?"✓ Video":"🎬 AI video"}</button><button className="mini aiButton" onClick={()=>generateVoiceover(s)} disabled={busyVoice===s.id}>{busyVoice===s.id?"…":sceneAudios[s.id]?"✓ Voice":"✨ AI voice"}</button><label className="upload">{images[s.id]?"✓ Image":"Add image"}<input type="file" accept="image/*" onChange={e=>{const f=e.target.files?.[0];if(f)attachImage(s.id,f)}}/></label></div></div>)}</div>}</div>
    </section>

    <section className="card cardAuto"><div className="cardHead"><div><h2>⚡ One-click AI media</h2><p>Generate missing images + AI voice-overs for every scene automatically.</p></div><button className="primary" onClick={generateAllMedia} disabled={!scenes.length||autoBusy}>{autoBusy?`Generating ${autoProgress}%…`:"✨ Generate All Media"}</button></div>{autoBusy&&<div className="progressWrap"><div className="progressBar"><i style={{width:`${autoProgress}%`}}/></div><span>{autoProgress}%</span></div>}</section>\n    <section className="card aiVideo"><div className="cardHead"><div><h2>4. AI video generator</h2><p>Server-side provider adapter keeps your API key out of the browser.</p></div><div className="videoControls"><label>Seconds <select value={duration} onChange={e=>setDuration(Number(e.target.value))}><option value={2}>2</option><option value={4}>4</option><option value={6}>6</option><option value={8}>8</option></select></label><button className="primary" onClick={generateVideo} disabled={!scenes.length||busyVideo||busySceneVideo!==null}>{busyVideo?"Generating…":"✨ Generate AI video"}</button></div></div>{aiVideoUrl&&<div className="aiVideoResult"><video src={aiVideoUrl} controls playsInline/><a className="download" href={aiVideoUrl} download="shree-ai-video-ai.mp4">⬇ Download AI video</a></div>}</section>
    <section className="card render"><div><h2>5. Final render</h2><p>Browser-rendered WebM with selectable aspect ratio, captions, transitions, music, AI scene voice-overs and real scene trim.</p></div><div className="renderControls"><label>Format <select value={aspect} onChange={e=>setAspect(e.target.value as typeof aspect)} disabled={rendering}><option value="9:16">9:16 Vertical</option><option value="16:9">16:9 Landscape</option><option value="1:1">1:1 Square</option></select></label><button className="primary" onClick={exportVideo} disabled={!scenes.length||rendering}>{rendering?`Rendering ${renderProgress}%…`:"Render final video"}</button></div>{rendering&&<div className="progressWrap"><div className="progressBar"><i style={{width:`${renderProgress}%`}}/></div><span>{renderProgress}%</span></div>}{status&&<div className="status">{status}</div>}{exportUrl&&<a className="download" href={exportUrl} download={`shree-ai-video-${aspect.replace(":","x")}.webm`}>⬇ Download WebM</a>}</section>
    <footer>Shree AI Video • captions • timeline • transitions • mixed music • AI media • browser rendering</footer>
  </main>;
}

function drawCaption(ctx:CanvasRenderingContext2D,text:string,style:"box"|"clean"|"neon",progress:number,width:number,height:number){
  const words=text.split(" ");let lines:string[]=[];let line="";
  for(const word of words){const test=line?line+" "+word:word;if(ctx.measureText(test).width>width*.82&&line){lines.push(line);line=word;}else line=test;}if(line)lines.push(line);
  const visible=Math.max(1,Math.ceil(lines.length*progress));const shown=lines.slice(0,visible);const y=height*.8-(shown.length-1)*height*.033;
  ctx.textAlign="center";ctx.font=`bold ${Math.max(24,Math.round(width*.047))}px system-ui`;
  if(style==="box"){ctx.fillStyle="rgba(0,0,0,.62)";ctx.fillRect(width*.06,y-height*.033,width*.88,shown.length*height*.035+height*.022);ctx.fillStyle="white";}
  else if(style==="neon"){ctx.shadowColor="#6da7ff";ctx.shadowBlur=18;ctx.fillStyle="white";}
  else {ctx.fillStyle="white";ctx.shadowColor="rgba(0,0,0,.9)";ctx.shadowBlur=8;}
  shown.forEach((line,i)=>ctx.fillText(line,width/2,y+i*height*.033));ctx.shadowBlur=0;
}